// lib/chapterIcons.js
//
// Logical emoji per chapter slug, chosen to suit each chapter's topic.
// Physics & Chemistry slugs are shared between JEE and NEET, so one map
// covers both. Unmapped chapters fall back to a per-subject default.

export const CHAPTER_EMOJI = {
  // ── Physics ──────────────────────────────────────────────
  "physical-world": "🌍",
  "units-and-measurements": "📏",
  "motion-straight-line": "🏃",
  "motion-plane": "🎯",
  "laws-of-motion": "⚖️",
  "work-energy-power": "⚡",
  "rotational-motion": "🌀",
  "gravitation": "🪐",
  "mechanical-properties-solids": "🧱",
  "mechanical-properties-fluids": "💧",
  "thermal-properties": "🌡️",
  "thermodynamics": "🔥",
  "kinetic-theory": "💨",
  "oscillations": "〰️",
  "waves": "🌊",
  "electric-charges-fields": "⚡",
  "electrostatic-potential-capacitance": "🔋",
  "current-electricity": "🔌",
  "moving-charges-magnetism": "🧲",
  "magnetism-matter": "🧲",
  "em-induction": "🔄",
  "alternating-current": "〽️",
  "em-waves": "📡",
  "ray-optics": "🔦",
  "wave-optics": "🌈",
  "dual-nature": "💡",
  "atoms": "⚛️",
  "nuclei": "☢️",
  "semiconductor-electronics": "💻",

  // ── Chemistry ────────────────────────────────────────────
  "basic-concepts": "🧪",
  "structure-of-atom": "⚛️",
  "periodic-table": "📋",
  "chemical-bonding": "🔗",
  "states-of-matter": "🌫️",
  "thermodynamics-chem": "🔥",
  "equilibrium": "⚖️",
  "redox-reactions": "🔋",
  "hydrogen": "🎈",
  "s-block": "🧂",
  "p-block-11": "🟦",
  "p-block-12": "🟪",
  "organic-basics": "🌿",
  "hydrocarbons": "⛽",
  "environmental-chemistry": "♻️",
  "solid-state": "💎",
  "solutions": "🧴",
  "electrochemistry": "🔋",
  "chemical-kinetics": "⏱️",
  "surface-chemistry": "🫧",
  "metallurgy": "⚙️",
  "d-f-block": "🥇",
  "coordination-compounds": "🔷",
  "haloalkanes-haloarenes": "🧫",
  "alcohols-phenols-ethers": "🍷",
  "aldehydes-ketones-acids": "🧪",
  "amines": "🐟",
  "biomolecules": "🧬",
  "polymers": "🪢",
  "chemistry-everyday-life": "💊",

  // ── Mathematics ──────────────────────────────────────────
  "sets": "🎛️",
  "relations-functions": "🔗",
  "relations-functions-12": "🔗",
  "trigonometric-functions": "📐",
  "inverse-trig": "📐",
  "mathematical-induction": "🪜",
  "complex-numbers-quadratic": "🌀",
  "linear-inequalities": "⚖️",
  "permutations-combinations": "🔢",
  "binomial-theorem": "➕",
  "sequences-series": "📶",
  "straight-lines": "📏",
  "conic-sections": "🥚",
  "intro-3d-geometry": "🧊",
  "limits-derivatives": "📉",
  "mathematical-reasoning": "🧠",
  "statistics": "📊",
  "probability-11": "🎲",
  "matrices": "🔲",
  "determinants": "🔳",
  "continuity-differentiability": "📈",
  "application-derivatives": "📐",
  "integrals": "∫",
  "application-integrals": "📐",
  "differential-equations": "🌀",
  "vector-algebra": "➡️",
  "three-d-geometry": "🧊",
  "linear-programming": "📊",
  "probability-12": "🎲",

  // ── Biology (NEET) ───────────────────────────────────────
  "living-world": "🌱",
  "biological-classification": "🗂️",
  "plant-kingdom": "🌿",
  "animal-kingdom": "🦁",
  "morphology-flowering-plants": "🌸",
  "anatomy-flowering-plants": "🌾",
  "structural-organisation-animals": "🐛",
  "cell-unit-life": "🔬",
  "biomolecules-bio": "🧬",
  "cell-cycle-division": "🧫",
  "transport-in-plants": "💧",
  "mineral-nutrition": "🌿",
  "photosynthesis": "☀️",
  "respiration-plants": "🍃",
  "plant-growth-development": "🌱",
  "digestion-absorption": "🍽️",
  "breathing-exchange-gases": "🫁",
  "body-fluids-circulation": "🩸",
  "excretory-products": "🚽",
  "locomotion-movement": "🦴",
  "neural-control": "🧠",
  "chemical-coordination": "⚗️",
  "reproduction-organisms": "🐣",
  "sexual-reproduction-flowering": "🌷",
  "human-reproduction": "👶",
  "reproductive-health": "❤️",
  "inheritance-variation": "🧬",
  "molecular-basis-inheritance": "🧬",
  "evolution": "🐒",
  "human-health-disease": "🏥",
  "food-production": "🌾",
  "microbes-human-welfare": "🦠",
  "biotechnology-principles": "🧫",
  "biotechnology-applications": "💉",
  "organisms-populations": "👥",
  "ecosystem": "🌳",
  "biodiversity-conservation": "🦋",
  "environmental-issues": "🌍",

  // ── SSC Quantitative Aptitude ────────────────────────────
  "number-system": "🔢",
  "simplification": "➗",
  "percentage": "％",
  "ratio-proportion": "⚖️",
  "average": "📊",
  "profit-loss-discount": "💰",
  "interest": "🏦",
  "mixture-alligation": "🧪",
  "time-work": "⏳",
  "pipes-cisterns": "🚰",
  "time-speed-distance": "🚗",
  "problems-trains": "🚆",
  "boats-streams": "⛵",
  "algebra": "🔤",
  "geometry": "📐",
  "mensuration": "📦",
  "trigonometry-ssc": "📐",
  "heights-distances": "🗼",
  "statistics-di": "📈",

  // ── SSC Reasoning ────────────────────────────────────────
  "analogy": "🔗",
  "classification": "🗂️",
  "series": "📶",
  "coding-decoding": "🔐",
  "blood-relations": "👨‍👩‍👧",
  "order-ranking": "🥇",
  "direction-distance": "🧭",
  "mathematical-operations": "➗",
  "puzzles-seating": "🪑",
  "syllogism": "🔵",
  "non-verbal": "🖼️",
  "venn-diagrams": "⭕",
  "statement-conclusions": "💬",
  "clock-calendar": "🕐",

  // ── SSC English ──────────────────────────────────────────
  "reading-comprehension": "📖",
  "spot-error": "🔍",
  "sentence-improvement": "✏️",
  "fill-blanks": "⬜",
  "synonyms-antonyms": "🔄",
  "one-word-substitution": "1️⃣",
  "idioms-phrases": "💭",
  "cloze-test": "📝",
  "active-passive": "🔁",
  "direct-indirect": "🗣️",
  "sentence-rearrangement": "🔀",
  "spelling-correction": "🔤",

  // ── SSC General Awareness ────────────────────────────────
  "history": "🏛️",
  "geography": "🗺️",
  "polity-constitution": "⚖️",
  "indian-economy": "💹",
  "general-science-phy-chem": "🔬",
  "general-science-biology": "🧬",
  "computer-technology": "💻",
  "current-affairs": "📰",
  "sports-awards-books": "🏆",
  "art-culture-static": "🎭",
};

// Per-subject fallback when a chapter slug isn't in the map above.
export const SUBJECT_FALLBACK_EMOJI = {
  physics: "⚛️",
  chemistry: "🧪",
  mathematics: "📐",
  biology: "🧬",
  botany: "🌿",
  zoology: "🐾",
  "quantitative-aptitude": "🔢",
  "general-intelligence-reasoning": "🧩",
  "english-comprehension": "📖",
  "general-awareness": "🌍",
};

export function chapterEmoji(chapterSlug, subjectSlug) {
  return CHAPTER_EMOJI[chapterSlug] || SUBJECT_FALLBACK_EMOJI[subjectSlug] || "📘";
}

export const SUBJECT_EMOJI = {
  physics: "⚛️",
  chemistry: "🧪",
  mathematics: "📐",
  maths: "📐",
  biology: "🧬",
  botany: "🌿",
  zoology: "🐾",
  "general-intelligence-reasoning": "🧩",
  reasoning: "🧩",
  "general-awareness": "🌍",
  "quantitative-aptitude": "🔢",
  "english-comprehension": "📖",
  english: "📖",
};
export function subjectEmoji(slug) { return SUBJECT_EMOJI[slug] || "📚"; }
